# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: 'Julien Perez - Machine Learning & AI Research Professor'
# Website URL
baseURL: 'https://perezjln.github.io/'

# Theme
theme: 'hugo-blox-builder'

############################
## LANGUAGE & SEO
############################

languageCode: 'en-US'
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: true
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
canonifyURLs: false
relativeURLs: false
rssLimit: 20
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: Lanczos
  quality: 80
  anchor: Smart
timeout: "600s"
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
  goldmark:
    renderer:
      unsafe: true
security:
  _merge: deep
sitemap:
  _merge: deep
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
